### ISSUE TITLE
paypal err

### ISSUE THREAD

**Issue by asigraph** [cabbagecreek/Marlin3DprinterTool#116]
hi
i get err on donet buton &cenot make donetion
![default](https://cloud.githubusercontent.com/assets/2701564/22826891/775f118e-ef9d-11e6-9d4b-c78fb5f6b13f.PNG)

thenks

**Comment by cabbagecreek** [comment]
I think the problem is oexploaterat.exe

I will change this to use prefered web browser.

**Comment by cabbagecreek** [comment]
The update is done.. Will be available at 0.19-beta and I think I will release that version during the weekend

**Comment by asigraph** [comment]
did u fix it?
i want to get the key but how to pay?

**Comment by cabbagecreek** [comment]
I have not released the v0.19-beta yet..

Send me a mail with name and mail-adress and I will send you the license key..

Another way to do a donation is to use Patreon:
https://www.patreon.com/user?u=3753058

I will soon start 2 other project on Patreon:
* The NEMA17 bowden motor. A gear-reduction that has the dimension of a NEMA17 motor and a flexi-drive. This "dummy-Nema17" moror replaces the extruder NEMA17. The "real-NEMA17" is mounted on the frame and the flexi-shaft transfer the force. This NEMA17 solution is about 10 times stronger than the direct driven.

* The touchless filament sensor. Counts the filament used on spool and on the actual print.
The LCD display shows the counters. The sensor is connected to Marlin thru I2C and can get its commands from GCODE (=reset part-filament counter at start of print)
The sensor can meassure the width of the filament and report thar to Marlin as volt where 1.83mm = 1.83V. 
The sensor can reacht on "end-of-filament" and send the signal to Marlin.
The sensor can detect that filament is not moving and send the signal to Marlin.

**Comment by Psyc0Flyer** [comment]
I have tried to donate also. What is your email?

**Comment by cabbagecreek** [comment]
There is a bug if you have another prefered webbrowser and some kind of antivirus.  ( iexplorer have alot of mysterious jox. Do anyone use it anymore?)

On v0.19-beta the donation button use the prefered webbrowser. 

C a b b a g e C r e e k (a) g m a i l . C o m

Its possible to donate thru patrion. I think the pledge is even better there 😇

Skickat från min iPhone

**Comment by asigraph** [comment]
Hi
My mail is  asigraph@gmail.com
Thenx

בתאריך 15 בפבר׳ 2017 14:15,‏ "Johnny Lindén" <notifications@github.com> כתב:

**Comment by cabbagecreek** [comment]
The v0.19-beta should use the prefered webbrowser.

This should solve the problem.  I colese the issue when I get the first donation from Paypal

**Comment by ate-it** [comment]
Version 19 still contains this error.

```

System.IO.FileNotFoundException: Could not load file or assembly 'PayPal, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'PayPal, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Marlin3DprinterTool.FrmMarlin3DprinterTool.btnPayPal_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by cabbagecreek** [comment]
I will do a hotfix on this.

JackWetson: Send me am email at c a b b a g e c r e e k (a) g m a i l . c o m

an d I will fix this ASAP

**Comment by cabbagecreek** [comment]
JackWetson

I have tested this and it worked with Chrome..

Look in the C:\program (x86)\marlin3dprintertool directory and se if you see the file PayPal.dll.


My suggestion is to uninstall marlin3Dprinter and delete all files inside  C:\program (x86)\marlin3dprintertool directory

Then reinstall the MSI again..

contact me thru mail , facebook or G+/hangout. We fix this in notime ;-)

**Comment by ate-it** [comment]
OK, so I did an un-install which removed the folder fully anyway. Paypal.ddl now exists however a new error

`System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**Comment by cabbagecreek** [comment]
Ok.. 
I will create my own webbrowser instead of using the one that should be installed (iexplerer.exe) or any other prefered webbrowser.

This will be a very small webbrowser that only covers the need for PayPal..

I will have this don very soon

**Comment by cabbagecreek** [comment]
I have done a Chrome webbrowser just for PayPal donations.. That part of M3DpT is 5 times bigger than the actual SW.

The new MSI us uploaded to Release without changing version.
You will have to unnstall and remove C:\program (x86)\Marlin3DprinterTool and then do a Installation with the new MSI.

**Comment by cabbagecreek** [comment]
Skickat från min iPhone

**Comment by cabbagecreek** [comment]
In ver 0.21-beta I think all PayPal problems are solved
