### ISSUE TITLE
Delta 3D version

### ISSUE THREAD

**Issue by sns5400** [cabbagecreek/Marlin3DprinterTool#121]
Hello,
Ar you provid a Delta version ? it look great

**Comment by cabbagecreek** [comment]
The delta type of printer is a bit different. Some parts of the software will work.
This is whats going to work:
* Endstop testing  (but not Z endstop and BLTouch. Its designed that way )
* Z-probe offset
*The Surfacescan feature is done for squere bed surface. If you choose the bed corners within the round surface you get a squere scan of a round bedsurface. (even if you cant do the bed-level)

*Configuration of Z-probe
*PID will work
* Extruder calibration
* Z-Maintenence. (perfect to find spots where binding occurs.. and oil the rods)
* Calculations 
* The STL Thumbnail in Windows explorer 
* The STL viewer
* The Marlin Editor 

The features that not will work is:
* Bed-level is for squere bedsurface only. Need to create a 3 point adjustment.

The reason that the 3 corner is deleted from the software is that its VERY difficult to create a affin transformation on a triangular surface. Its a mathematical challenge ;-)
I might give it a try (again) but in a separate tab that are deticated for delta printers.
Last time the development took almost a month but the quest is filled with rabbit pitholes and within the pithole there is even more pitholes... I know some of them now and I might be able to avoid them (but I will find new ;-)
