### ISSUE TITLE
Problem upgrading config file

### ISSUE THREAD

**Issue by batata004** [cabbagecreek/Marlin3DprinterTool#125]
Hi,

First I appreciate this great piece of work! But I am trying to migrate the old Marlin configuratino files attached to the newest marlin firmware version but it doesnt look to work. Do you know if your project supports migrating old config files to new version of marlin?
[Configuration_adv.txt](https://github.com/cabbagecreek/Marlin3DprinterTool/files/877211/Configuration_adv.txt)
[Configuration.txt](https://github.com/cabbagecreek/Marlin3DprinterTool/files/877212/Configuration.txt)

**Comment by cabbagecreek** [comment]
You should look at https://www.youtube.com/watch?v=xkgaal_oll4

This might help you
