### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by Googliola** [cabbagecreek/Marlin3DprinterTool#145]
The program starts, but as I try to connect to my board the app is either freezing (on correct port) or populating the GUI with (default?) values when I select some other port. 
Just to rule out any mistake on my side: Arduino IDE / Serial Monitor etc can connect

Version 0.23.6332.21935 (Windows 7 and 8.1 x64)

**Comment by cabbagecreek** [comment]
I have released v0.26-beta and this issue is solved

I have done alot on COM-port search and assigning the combobox with values.

May need some more data on this

**Comment by cabbagecreek** [comment]
Fixed in release v0.27-beta

**Comment by venuasg** [comment]
Hi,

I have the same issue, unable to connect.
I am using Marlin3DPrinterTool version : 0.28.6705.20684.
