### ISSUE TITLE
Thank you for making this!

### ISSUE THREAD

**Issue by PolloPequeno** [cabbagecreek/Marlin3DprinterTool#146]
Greetings from New Hampshire, USA.

Just a quick note to say how useful this software is, particularly the build surface scanner and the Marlin editor.

Please let me know if you need any help testing new features/updates.

Best,
Tyler

**Comment by PolloPequeno** [comment]
Please send me the v0.24-beta msi.

my Z offset is -.2

Lonczakt@gmail.com

Thanks again,
Tyler

**Comment by cabbagecreek** [comment]
I have released v0.26-beta
