### ISSUE TITLE
Z-Axis Controll don´t work

### ISSUE THREAD

**Issue by arnold-b** [cabbagecreek/Marlin3DprinterTool#149]
Hello The control of Z-Axis don´t work. if i press Z- or Z+ it always go just one direction and i also can´t control how far it goes. Theres is no difference between 0.1 or 100

**Comment by cabbagecreek** [comment]
I will look at the Z-control. I put this as  an issue at Git

2018-02-12 22:49 GMT+01:00 arnold-b <notifications@github.com>:

**Comment by cabbagecreek** [comment]
I have released v0.26-beta and this issue is solved
