### ISSUE TITLE
Configure Bed - setting corners coors issue

### ISSUE THREAD

**Issue by glovax** [cabbagecreek/Marlin3DprinterTool#150]
Johnny,
when I was setting coords for left corner, clickingpin icon inputs wrong values int coordinates instead of e.g. x:14 y:35 it writes x:140 y: 350.
Tom

**Comment by cabbagecreek** [comment]
Add this aswell to Git.. Its a custom control that has gone bazoka..

Regards

2018-02-14 1:14 GMT+01:00 glovax <notifications@github.com>:

**Comment by cabbagecreek** [comment]
I have released v0.26-beta and this issue is solved
