### ISSUE TITLE
Configure Bed - Reverse logic doesn't work

### ISSUE THREAD

**Issue by glovax** [cabbagecreek/Marlin3DprinterTool#151]
As in  subject - reverse logic doesn't change orintation of screws turn.
Tom

**Comment by cabbagecreek** [comment]
I have added  this to Git

Regards

2018-02-14 1:19 GMT+01:00 glovax <notifications@github.com>:

**Comment by glovax** [comment]
Johnny,
Its already in Git. I posted it here. Just  now you've got two entries of this same issue. Is it by purpose?
T.

**Comment by cabbagecreek** [comment]
Ooops.. Not my intension .. I will join them


2018-02-14 12:09 GMT+01:00 glovax <notifications@github.com>:

**Comment by cabbagecreek** [comment]
I have released v0.26-beta and this issue is solved
