### ISSUE TITLE
Dock Z Probe function out of bed

### ISSUE THREAD

**Issue by glovax** [cabbagecreek/Marlin3DprinterTool#158]
Dock Z probe should be measured  "Safe_Home" position set up on "Configure bed" tab. Currently, when its working on home position, it means that in some printers nozzle is out of bed so its impossible to setup offset of probe against nozzle.
T.

**Comment by cabbagecreek** [comment]
I have released v0.26-beta and this issue is solved

Before  doing Z-prob offset it does a simulated "Safe-Home".. On 3d printers that have this in Firmware the procedure in not needed but this will be safer
