### ISSUE TITLE
"Nozzle Touching Bed" miscalculates Z_PROBE_OFFSET_FROM_EXTRUDER value

### ISSUE THREAD

**Issue by glovax** [cabbagecreek/Marlin3DprinterTool#159]
Z_PROBE_OFFSET_FROM_EXTRUDER value. There is also wrong equation. Old value should be used something .... strange.
correct eqution is:
new Z_PROBE_OFFSET_FROM_EXTRUDER = old Z_PROBE_OFFSET_FROM_EXTRUDER - current Z.

**Comment by cabbagecreek** [comment]
I have released v0.26-beta and this issue is solved

There is a totaly nev calculation on Z-probe offset
