### ISSUE TITLE
newer version installed

### ISSUE THREAD

**Issue by ikn369330** [cabbagecreek/Marlin3DprinterTool#160]
I am trying to install Marlin3dprintertool, I have removed it from every file and folded I can find, I have even removed it from my registry, however when I try to install it, I get the same message every time.. A newer version of Marlin3dprintertool is already installed. No matter how much I search for it, I can not find it anywhere on my laptop. any suggestions

**Comment by freddotu** [comment]
If no one else has the precise solution, consider to use the registry cleaner portion of CCleaner to purge registry remnants. I've found that often helps in installation glitches of this natuer.

**Comment by cabbagecreek** [comment]
I have released v0.26-beta and this issue is solved.

The installer contains option to install STL viewer /Thumbnail and/or M3DpT
