### ISSUE TITLE
Testing z-Probe

### ISSUE THREAD

**Issue by ghost** [cabbagecreek/Marlin3DprinterTool#161]
Measuring Z-Probe repeatability does not work. After the first calibration with the BLTouch no value is given and the process is stoped. The software is completely blocked and must be reset.

Version: 0.25.6607.18348
Marlin 1.1.8
Printer CR-10S
Using BLTouch

![zprobeoffset](https://user-images.githubusercontent.com/27200726/38600108-40d08d72-3d63-11e8-9fa3-052eaca7823e.JPG)

**Comment by ghost** [comment]
Already found the issue.
Z_MIN_PROBE_REPEATABILITY_TEST must be defined in Marlin
Line 726 Marlin 1.1.8 Configuration.h

**Comment by cabbagecreek** [comment]
Perfect!!. During 3Dmeetup in Sweden last weekend I was doing alot if improvements.
I have totaly rewritten the Z-probe offset calculation.

**Comment by cabbagecreek** [comment]
I have released v0.26-beta and this issue is solved
