### ISSUE TITLE
Connecting to printer

### ISSUE THREAD

**Issue by leeb65** [cabbagecreek/Marlin3DprinterTool#162]
Hi, I have a problem when I connect to the printer I get the following popup.

![image](https://user-images.githubusercontent.com/31450928/39092525-b0829abe-4607-11e8-85a2-a726631ec80f.png)

If I click the settings button the same popup shows twice.

Thanks

**Comment by cabbagecreek** [comment]
I see a spelling error:  ;-) this will be easy to find.. Will be fixed in v0.27-beta.

There is also an error in autoupdate that will be fixed at the same time

**Comment by cabbagecreek** [comment]
Fixed in release v0.27-beta
