### ISSUE TITLE
Config editor/Migration fails without admin rights

### ISSUE THREAD

**Issue by derpicknicker1** [cabbagecreek/Marlin3DprinterTool#17]
I have to start the software as administrator to use it as desired. When i try to set the paths for migration i get an error (by the way...you released the debug version 😄 ). 
Something like "Access forbidden for 'c:\Program Files (x86)\Marlin3Dprinter Tool\MarlinEditorConfiguration.xml'" (for me its in german).
Same notification now also on startup after updating to newest release.

Using up to date Win10.

**Comment by derpicknicker1** [comment]
Maybe you should use something like `Environment.SpecialFolder.MyDocuments` or `Environment.SpecialFolder.ApplicationData` as path for saving files. I think this is a problem of writing to the installation folder of the programm.

[More Informations on MSDN](https://msdn.microsoft.com/en-us/library/system.environment.specialfolder%28v=vs.110%29.aspx)

**Comment by cabbagecreek** [comment]
I will make an issue of this and try to correct this soon.

It is not my intension to do release in debug mode. I am a newbie on Git
and Gitflow but I try to be better. :-)

MANY REGARDS!!!!

2016-10-05 2:58 GMT+02:00 derpicknicker1 notifications@github.com:

**Comment by derpicknicker1** [comment]
The debug mode has nothing to do with github. You have to set this in VisualStudio build options(?)  (Debug/Release).
Debug mode is not really bad. Allows you to go on with the programm when a issue appears and the programm will normaly hang/close.

**Comment by cabbagecreek** [comment]
I have started the WiX installer to move the configuration files to
ProgramData. I have some time this evening to test this.

2016-10-05 11:42 GMT+02:00 derpicknicker1 notifications@github.com:

**Comment by cabbagecreek** [comment]
I have moved the config files to ProgramData
