### ISSUE TITLE
ScanSurface numberOfRepetitions is allways 1

### ISSUE THREAD

**Issue by cabbagecreek** [cabbagecreek/Marlin3DprinterTool#25]
Add multiple test of each probepoint

**Comment by Pipshag** [comment]
Just as a note, there is also included a define in the Marlin firmware to Double Touch with the probe. Might be good to document it as a suggestion for getting more reliable readings.

**Comment by cabbagecreek** [comment]
This is more than just the double-touch.. Its having multiple reads on each point and let the surface-chart calculate the average/ standard deviation...

**Comment by Pipshag** [comment]
Absolutely, I understand that - and it's a good way to do it. But whenever a documentation arises, I thought it might be nice to give some pointers on how to get as accurate readings as possible from the sensor. Like, general tips & tricks for configuring Marlin.

**Comment by cabbagecreek** [comment]
Multiple points done
