### ISSUE TITLE
Firmware Location has a default value

### ISSUE THREAD

**Issue by psavva** [cabbagecreek/Marlin3DprinterTool#46]
Upon opening the application, the Firmware location is pre-populated with:
C:\Users\Johnnyboy\Desktop\Marlin\Aktuell Rigidbot -- Marlin 1.1.0-RC7\Marlin-1.0.2-1\Marlin-1.0.2-1\Marlin

This should probably be blank on first start, and afterwards, should probably 'remember' the value at the time of last usage.

**Comment by cabbagecreek** [comment]
I make an issue of it

It will be stored in the ProgramData and you will only have to type /find
the directories once

Regards

2016-11-17 21:14 GMT+01:00 Panayiotis Savva notifications@github.com:

**Comment by cabbagecreek** [comment]
Default location is blank. Must be setup before use
