### ISSUE TITLE
Default PID values are duplicated in the dropdown list

### ISSUE THREAD

**Issue by psavva** [cabbagecreek/Marlin3DprinterTool#48]
I can see the values for
DEFAULT_Kp
DEFAULT_Ki
DEFAULT_Kd
and 
DEFAULT_bedKp
DEFAULT_bedKi
DEFAULT_bedKd

are duplicated 3 times in the dropdown

**Comment by cabbagecreek** [comment]
What version of Marlin

Send a screenshoot

2016-11-17 21:22 GMT+01:00 Panayiotis Savva notifications@github.com:

**Comment by psavva** [comment]
![image](https://cloud.githubusercontent.com/assets/1454758/20406253/3d1d1842-ad15-11e6-9cef-1a9d1d1dd053.png)

I'm using RC7

**Comment by cabbagecreek** [comment]
This looks like an older version of M3DPT..

2016-11-17 21:29 GMT+01:00 Panayiotis Savva notifications@github.com:

**Comment by cabbagecreek** [comment]
Uninstall and DELETE the files in C:\programfilesx86\Marlin3DprinterTool.  <== IMPORTANT!!

Then reinstall with the MSI you got in mail. The MSI you got in mail is the v0.13-beta 

Check if the problem still occur and make a note if it does

**Comment by cabbagecreek** [comment]
This is an old version. Fixed in the current version
