### ISSUE TITLE
Preview shows that a feature is commented, when in fact its in use.

### ISSUE THREAD

**Issue by psavva** [cabbagecreek/Marlin3DprinterTool#49]
![image](https://cloud.githubusercontent.com/assets/1454758/20406041/650589da-ad14-11e6-81a5-63993ea70b91.png)

You'll notice that the REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER is enabled in my firmware, but it appears as if it's striked out in the preview

**Comment by cabbagecreek** [comment]
Thats on old "RegExp" error.. The regulat expression is finding // from
previous row and adds 0-n spaces (including CRLF) and then #define

This should be corrected in v0.12-beta

Doublecheck when you have reinstalled the version I sent in mail

2016-11-17 21:24 GMT+01:00 Panayiotis Savva notifications@github.com:

**Comment by cabbagecreek** [comment]
This was an issue in old version.. Should work in latest version
