### ISSUE TITLE
Maximizing the application doesn't behave properly 

### ISSUE THREAD

**Issue by psavva** [cabbagecreek/Marlin3DprinterTool#50]
I maxamized the application.
It's expeceted that the edit boxes fill the screen.

They remain the same size, and give me a lot of 'grey' area on the screen.

My resolution is 1080p

**Comment by cabbagecreek** [comment]
That is definitly an area where I have not worked so hard.. I will look at
all the resize problem and make it possible to use the entire screen

2016-11-17 21:25 GMT+01:00 Panayiotis Savva notifications@github.com:

**Comment by cabbagecreek** [comment]
When optimizing for 1360x768 this is fixed
