### ISSUE TITLE
Clicking Connect, I get a message for the Demo version

### ISSUE THREAD

**Issue by psavva** [cabbagecreek/Marlin3DprinterTool#54]
When clicking on the connect button, I'm prompted with a message saying Demo Version.

That is not expected....

![image](https://cloud.githubusercontent.com/assets/1454758/20406483/341b93e4-ad16-11e6-994c-6af16f7d5bcf.png)

**Comment by cabbagecreek** [comment]
Have you installed the latest version and used the setup button (next to
connect) and entered the key that you got in previous mail

2016-11-17 21:35 GMT+01:00 Panayiotis Savva notifications@github.com:

**Comment by cabbagecreek** [comment]
The v0.13-beta is the first version that contains the License feature. It will be released during the weekend.
