### ISSUE TITLE
Choosing a Folder with no marlin - no message is raised

### ISSUE THREAD

**Issue by psavva** [cabbagecreek/Marlin3DprinterTool#57]
When choosing a folder, which is NOT Marlin, there is no indication that anything is wrong (except for the exception raised, which I mentioned earlier in another incident raised)

At minimum, there should be a message warning the user that the configuration file was not specified.

You probably want to clear the current configuration that is also loaded in this case.

**Comment by cabbagecreek** [comment]
I will check that the directory is containing malin.ino and configuration.h and arduino.exe.
If not a message will be shown that its is not a directory for Marlin FW or ArduinoIDE

**Comment by cabbagecreek** [comment]
I have fixed this Issue and testing that configuration.h and marlin.ino is existing
