### ISSUE TITLE
Suggestion: Able to control Z-jump on probing

### ISSUE THREAD

**Issue by Pipshag** [cabbagecreek/Marlin3DprinterTool#60]
I would want to be able to specifiy the Z-jump height when probing the bed. I do not use "Engage the Z-probe" since it's a fixed probe with enough clearance already.

The reasoning is that it's quite unnecessary to jump 10 mm on probe moves when I normally use 2 mm.

**Comment by cabbagecreek** [comment]
This is for safety reason..  I have banged to many expensive sensors in the
bed and both distroyed sensors, mounting and nozzles.

I will look at this at make it changeable with a default of 10mm... When
the function is working it can be reduced to 2mm

2016-11-18 10:01 GMT+01:00 Carl-Christian Ljunggren <
notifications@github.com>:

**Comment by Pipshag** [comment]
Thanks! The scanning takes too long time for rerunning it. Had to optimize it when I ran ABL 4x4.

**Comment by cabbagecreek** [comment]
The amount of lift between probing is added to "Configure z-probe".. I start with 50 and change to 5 and the 1.. It has to be at least 1.

**Comment by Pipshag** [comment]
Great, that's awesome!

**Comment by cabbagecreek** [comment]
I belive that we can close this one.. 13 left to go ;-)
