### ISSUE TITLE
Suggestion: Scan Buildsurface orientation indicator

### ISSUE THREAD

**Issue by Pipshag** [cabbagecreek/Marlin3DprinterTool#62]
I would suggest to either present a tooltip or axis on the model to be able to orientate. It might even be as easy as to list the order of probes and numerical value to have some reference.

**Comment by cabbagecreek** [comment]
Make a simple "paint" picture of a screenshoot..

2016-11-18 10:58 GMT+01:00 Carl-Christian Ljunggren <
notifications@github.com>:

**Comment by Pipshag** [comment]
I'm stupid, there's a perfectly good coordinate system in the matrix. Closing.
