### ISSUE TITLE
Support for several tools

### ISSUE THREAD

**Issue by Pipshag** [cabbagecreek/Marlin3DprinterTool#66]
Neither **PID** nor **Extruder Calibration** supports setting different tools. I'm using dual extruders and would appreciate setting the tool to be used before running the commands.

**Comment by cabbagecreek** [comment]
As soon as PID and Extruder Calibration is working flawless, a GUI control will be added and extruder can be choosen. For now its only one extruder..
This is a quick fix and I have already prepared for it

**Comment by cabbagecreek** [comment]
The "quickfix" is now done (1½ month later ;-)

This is fixed in v0.16-beta
