### ISSUE TITLE
Suggestion: Ability to clear projection in Scan buildsurface

### ISSUE THREAD

**Issue by Pipshag** [cabbagecreek/Marlin3DprinterTool#68]
I have run a probe to get a buildsurface indication in the 3D model. I then went and read in the currently saved Mesh. That means I have two different scans which are great to confirm if I actually did a good job earlier.

Problem is, I would now want to watch only the previous Mesh layout and can't find a button to reset the view and remove everything!

**Comment by cabbagecreek** [comment]
This is actually not a bug.. Its a feature ;-)  
Doing Bed leveling and overlay mesh should create 2 paralell surfaces.
I use this during develop to confirm that MBL has a valid output.

I will add a Reset chart button.

**Comment by cabbagecreek** [comment]
Reset button added
