### ISSUE TITLE
Scrolling in the communications window is backwards.

### ISSUE THREAD

**Issue by cbitterfield** [cabbagecreek/Marlin3DprinterTool#79]
(The first stays on top). It should work like tail.
Also I see a M119 constantly being sent. (You really can't read the logs. 
Probably need a pause on scroll.
![serialcapture](https://cloud.githubusercontent.com/assets/11802951/21142363/c27e3a8a-c10f-11e6-84d8-6541a8182053.PNG)

**Comment by cabbagecreek** [comment]
I am working on the Marlin Editor to make the migration to Marlin RC8 as easy as possible. The RS232 monitor uses part of the same code.  

By looking at the screenshoot I can tell that you are using an older version.

v0.12-beta have a new checkbox to remove the "busy processing" messages. (It can be removed in Firmware aswell)

There is also a commandline where you can send commands and the combobox stores all commands within a connection.

![image](https://cloud.githubusercontent.com/assets/713313/21153347/64656918-c16a-11e6-8854-ed35db0f1a41.png)

**Comment by cabbagecreek** [comment]
The M119 is to check Endstop. For each responnce from M119 there is a new M119 sent. 
This is just the case when Endstop TAB is active. If some other tab is active the M119/Endstop is mute

**Comment by cabbagecreek** [comment]
+cbitterfield 
Can this be closed?
