### ISSUE TITLE
Endstop Tab - Enhancement Request

### ISSUE THREAD

**Issue by cbitterfield** [cabbagecreek/Marlin3DprinterTool#81]
Endstop Tab
On Endstop Tab; it would be nice to show the Z-Probe status. Mine is connected to Pin 57; I’d like to know the reporting status of the Z-Probe (On/Off) for trouble shooting.

**Comment by cabbagecreek** [comment]
Alot is done in the v0.12-beta version (more to come)
![virtualdialgauge](https://cloud.githubusercontent.com/assets/713313/21153146/8519cb78-c169-11e6-8083-1848f6ef18ae.png)

The missing part is M48 probe testing and G30.. I think taht will be v0.14-beta

Give me more suggestions of what you want to see

**Comment by cabbagecreek** [comment]
+cbitterfield 
Alot of improvements are done in v0.14-beta. Can this be closed?
