### ISSUE TITLE
Display Relevant Information - Enhancement

### ISSUE THREAD

**Issue by cbitterfield** [cabbagecreek/Marlin3DprinterTool#82]
It would help if there was a place that displayed:
X Y Z Coordinates in MM and Steps
Temperatures for all thermistors

**Comment by cabbagecreek** [comment]
The x Y and Z are visible in v0.17-beta

Still needs temperature

**Comment by cabbagecreek** [comment]
Merge pull request #112 from cabbagecreek/develop

Contains the missing temperature info. The fields are above the tempchart

This will be available in v0.18-beta release

**Comment by cabbagecreek** [comment]
The 0.18-beta is released and this issue is solved
