### ISSUE TITLE
scan the bed surface (Not working / Lock up)

### ISSUE THREAD

**Issue by cbitterfield** [cabbagecreek/Marlin3DprinterTool#84]
When I try to scan the bed surface; there is a runaway memory issue. It climbs to 2-4 GB of RAM real fast with no way to stop it except for “end task”
[error.txt](https://github.com/cabbagecreek/Marlin3DprinterTool/files/649063/error.txt)
![scanmemcapture](https://cloud.githubusercontent.com/assets/11802951/21142544/b4166ed0-c110-11e6-8d6e-73df53c7e5a4.PNG)

I attached my configuration.h file for reference.

[configuration_h.txt](https://github.com/cabbagecreek/Marlin3DprinterTool/files/649072/configuration_h.txt)

**Comment by cabbagecreek** [comment]
Try to install the v0.12-beta and test if the problems still exist
