### ISSUE TITLE
Display Software Version - Enhancement

### ISSUE THREAD

**Issue by cbitterfield** [cabbagecreek/Marlin3DprinterTool#85]
Show software version (and build number) in Window header or about box

**Comment by cabbagecreek** [comment]
This is available in v0.12-beta. Do you have the latest version installed?
![image](https://cloud.githubusercontent.com/assets/713313/21152904/9cf8deec-c168-11e6-9780-a7f46a329fa5.png)

There is also setters for some values.

If you yse Read EEPROM you get almost all parameters as you get when the RS232 connection to the printer is done.

**Comment by cabbagecreek** [comment]
Both Marlin3DprinterTool version (In titlebar) and Marlin FW version is visible in v0.14-beta


![image](https://cloud.githubusercontent.com/assets/713313/21227013/5e09a66e-c2d8-11e6-8c2f-8ce417fc5387.png)

+cbitterfield
Close this issue if the new version is working

**Comment by cbitterfield** [comment]
I loaded the Beta (Once I figured out that it was further along on the code base). Installer says it is not.

Still having some issues with it. Lots of long delays. When I have a chance to revisit, I’ll provide some better feedback


-------------------------------------------
Colin Bitterfield
mailto:colin@bitterfield.com
phone: (571) 533-4700
https://www.linkedin.com/in/colin-bitterfield-80612327
-------------------------------------------

On December 15, 2016 at 9:08:51 AM, Johnny Lindén (notifications@github.com) wrote:

Both Marlin3DprinterTool version (In titlebar) and Marlin FW version is visible in v0.14-beta



+cbitterfield
Close this issue if the new version is working

**Comment by cabbagecreek** [comment]
Have you downloaded the v0.16-beta?


2017-01-09 22:14 GMT+01:00 cbitterfield <notifications@github.com>:

> I loaded the Beta (Once I figured out that it was further along on the
> code base). Installer says it is not.
>
> Still having some issues with it. Lots of long delays. When I have a
> chance to revisit, I’ll provide some better feedback
>
>
> -------------------------------------------
> Colin Bitterfield
> mailto:colin@bitterfield.com
> phone: (571) 533-4700
> https://www.linkedin.com/in/colin-bitterfield-80612327
> -------------------------------------------
>
> On December 15, 2016 at 9:08:51 AM, Johnny Lindén (

**Comment by cbitterfield** [comment]
No, but I will tonight.

-------------------------------------------
Colin Bitterfield
mailto:colin@bitterfield.com
phone: (571) 533-4700
https://www.linkedin.com/in/colin-bitterfield-80612327
-------------------------------------------

On January 9, 2017 at 4:16:02 PM, Johnny Lindén (notifications@github.com) wrote:

Have you downloaded the v0.16-beta?


2017-01-09 22:14 GMT+01:00 cbitterfield <notifications@github.com>:

> I loaded the Beta (Once I figured out that it was further along on the
> code base). Installer says it is not.
>
> Still having some issues with it. Lots of long delays. When I have a
> chance to revisit, I’ll provide some better feedback
>
>
> -------------------------------------------
> Colin Bitterfield
> mailto:colin@bitterfield.com
> phone: (571) 533-4700
> https://www.linkedin.com/in/colin-bitterfield-80612327
> -------------------------------------------
>
> On December 15, 2016 at 9:08:51 AM, Johnny Lindén (

**Comment by cabbagecreek** [comment]
Read the instructions on the release page.. This 0.16-beta has so many new
features yhat its almost a totaly new program

2017-01-09 22:17 GMT+01:00 cbitterfield <notifications@github.com>:

> No, but I will tonight.
>
> -------------------------------------------
> Colin Bitterfield
> mailto:colin@bitterfield.com
> phone: (571) 533-4700
> https://www.linkedin.com/in/colin-bitterfield-80612327
> -------------------------------------------
>
> On January 9, 2017 at 4:16:02 PM, Johnny Lindén (notifications@github.com)
> wrote:
>
> Have you downloaded the v0.16-beta?
>
>
> 2017-01-09 22:14 GMT+01:00 cbitterfield <notifications@github.com>:
>
> > I loaded the Beta (Once I figured out that it was further along on the
> > code base). Installer says it is not.
> >
> > Still having some issues with it. Lots of long delays. When I have a
> > chance to revisit, I’ll provide some better feedback
> >
> >
> > -------------------------------------------
> > Colin Bitterfield
> > mailto:colin@bitterfield.com
> > phone: (571) 533-4700
> > https://www.linkedin.com/in/colin-bitterfield-80612327
> > -------------------------------------------
> >
> > On December 15, 2016 at 9:08:51 AM, Johnny Lindén (

**Comment by cbitterfield** [comment]
OK

-------------------------------------------
Colin Bitterfield
mailto:colin@bitterfield.com
phone: (571) 533-4700
https://www.linkedin.com/in/colin-bitterfield-80612327
-------------------------------------------

On January 9, 2017 at 4:18:55 PM, Johnny Lindén (notifications@github.com) wrote:

Read the instructions on the release page.. This 0.16-beta has so many new
features yhat its almost a totaly new program

2017-01-09 22:17 GMT+01:00 cbitterfield <notifications@github.com>:

> No, but I will tonight.
>
> -------------------------------------------
> Colin Bitterfield
> mailto:colin@bitterfield.com
> phone: (571) 533-4700
> https://www.linkedin.com/in/colin-bitterfield-80612327
> -------------------------------------------
>
> On January 9, 2017 at 4:16:02 PM, Johnny Lindén (notifications@github.com)
> wrote:
>
> Have you downloaded the v0.16-beta?
>
>
> 2017-01-09 22:14 GMT+01:00 cbitterfield <notifications@github.com>:
>
> > I loaded the Beta (Once I figured out that it was further along on the
> > code base). Installer says it is not.
> >
> > Still having some issues with it. Lots of long delays. When I have a
> > chance to revisit, I’ll provide some better feedback
> >
> >
> > -------------------------------------------
> > Colin Bitterfield
> > mailto:colin@bitterfield.com
> > phone: (571) 533-4700
> > https://www.linkedin.com/in/colin-bitterfield-80612327
> > -------------------------------------------
> >
> > On December 15, 2016 at 9:08:51 AM, Johnny Lindén (
