### ISSUE TITLE
Display truncated in Y on resolution 1280 x 1024

### ISSUE THREAD

**Issue by LeChuck71** [cabbagecreek/Marlin3DprinterTool#87]
Issue post from Google+
The title says it all

**Comment by cabbagecreek** [comment]
Test in new release v0.14-beta

Minimum size is 1268x720

+LeChuck71
Close this issue after testing that the new size is working

**Comment by LeChuck71** [comment]
Trying to test it this evening

**Comment by LeChuck71** [comment]
Everything looks fine on 1280 x 1024
